### ISSUE TITLE
Contract Byte Code Error

### ISSUE THREAD

**Issue by iegestesi** [halls7588/ERC20-Token-and-ICO-Contract#3]
I create a contract first. Then I write the byte code that I want to create a contract for ico. Mew doesn't charge me gas. In order to send tokens, an ico contract must be created, right? I do not understand the code I say I have a problem I am doing a due diligence. ico contract doesn't occur so I can send tokens there. I'm telling you it couldn't happen, and you write me a different answer.

If you look at the photo I sent, I put your current code without changing, but it did not give me the gas fee. I created a normal contract. But I can't create a contract for sale. I'il send a token here if I can.

<a href="https://ibb.co/2y8q48g"><img src="https://i.ibb.co/JKxnJx5/test.jpg" alt="test" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>image hosting</a><br />

_Originally posted by @iegestesi in https://github.com/halls7588/ERC20-Token-and-ICO-Contract/issues/2#issuecomment-537882136_

**Comment by halls7588** [comment]
This is an error with MEW of whatever compiler you are using. Please ensure that you are using the correct version of Solidity and that you are using the EVM code and Byte Code appropriately.

**Comment by iegestesi** [comment]
I'm doing the same version of what the pragma version says. I'm pasting that byte code. Mew also don't know how it could be a mistake.
